### ISSUE TITLE
Add a reference to the contributing guide

### ISSUE THREAD

**Issue by jamesgeorge007** [jamesgeorge007/scaffold-static#10]
Include a new section within `README.md` that links up to the `contributing guidelines`.
To be done once #9 is resolved.

**Comment by ivaibhavjindal** [comment]
I'd like to work on this just want to know what should the heading for the hyperlink be?

**Comment by jamesgeorge007** [comment]
```md
## Contributing

Please see the [contributing guidelines](url)
