### ISSUE TITLE
Move contributing guidelines to a dedicated file

### ISSUE THREAD

**Issue by jamesgeorge007** [jamesgeorge007/scaffold-static#9]
It is a good practice to have a dedicated `contributing.md` where all the contributing guidelines can be found. Move the respective content from `README` to the newly created file.

**Comment by ivaibhavjindal** [comment]
Hi @jamesgeorge007, I'd like to work on this. Can you please assign this to me?

**Comment by jamesgeorge007** [comment]
> Hi @jamesgeorge007, I'd like to work on this. Can you please assign this to me?

@ivaibhavjindal are you participating as a student as part of [JWOC](https://jwoc.tech/) ?

**Comment by ivaibhavjindal** [comment]
Yes, I am.

**Comment by jamesgeorge007** [comment]
Sure, go on :+1:

**Comment by ivaibhavjindal** [comment]
I had a little query whether I should move How to contribute part only to contributing.md or the Why contribute part as well?

**Comment by jamesgeorge007** [comment]
> I had a little query whether I should move How to contribute part only to contributing.md or the Why contribute part as well?

Yeah, both of em.
